const US_STATES = [
    { id: 1, name: 'ALABAMA', abbreviation: 'AL'},
    { id: 2, name: 'ALASKA', abbreviation: 'AK'},
    { id: 3, name: 'ARIZONA', abbreviation: 'AZ'},
    { id: 4, name: 'ARKANSAS', abbreviation: 'AR'},
    { id: 5, name: 'CALIFORNIA', abbreviation: 'CA'},
    { id: 6, name: 'COLORADO', abbreviation: 'CO'},
    { id: 7, name: 'CONNECTICUT', abbreviation: 'CT'},
    { id: 8, name: 'DELAWARE', abbreviation: 'DE'},
    { id: 9, name: 'FLORIDA', abbreviation: 'FL'},
    { id: 10, name: 'GEORGIA', abbreviation: 'GA'},
    { id: 11, name: 'HAWAII', abbreviation: 'HI'},
    { id: 12, name: 'IDAHO', abbreviation: 'ID'},
    { id: 13, name: 'ILLINOIS', abbreviation: 'IL'},
    { id: 14, name: 'INDIANA', abbreviation: 'IN'},
    { id: 15, name: 'IOWA', abbreviation: 'IA'},
    { id: 16, name: 'KANSAS', abbreviation: 'KS'},
    { id: 17, name: 'KENTUCKY', abbreviation: 'KY'},
    { id: 18, name: 'LOUISIANA', abbreviation: 'LA'},
    { id: 19, name: 'MAINE', abbreviation: 'ME'},
    { id: 20, name: 'MARYLAND', abbreviation: 'MD'},
    { id: 21, name: 'MASSACHUSETTS', abbreviation: 'MA'},
    { id: 22, name: 'MICHIGAN', abbreviation: 'MI'},
    { id: 23, name: 'MINNESOTA', abbreviation: 'MN'},
    { id: 24, name: 'MISSISSIPPI', abbreviation: 'MS'},
    { id: 25, name: 'MISSOURI', abbreviation: 'MO'},
    { id: 26, name: 'MONTANA', abbreviation: 'MT'},
    { id: 27, name: 'NEBRASKA', abbreviation: 'NE'},
    { id: 28, name: 'NEVADA', abbreviation: 'NV'},
    { id: 29, name: 'NEW HAMPSHIRE', abbreviation: 'NH'},
    { id: 30, name: 'NEW JERSEY', abbreviation: 'NJ'},
    { id: 31, name: 'NEW MEXICO', abbreviation: 'NM'},
    { id: 32, name: 'NEW YORK', abbreviation: 'NY'},
    { id: 33, name: 'NORTH CAROLINA', abbreviation: 'NC'},
    { id: 34, name: 'NORTH DAKOTA', abbreviation: 'ND'},
    { id: 35, name: 'OHIO', abbreviation: 'OH'},
    { id: 36, name: 'OKLAHOMA', abbreviation: 'OK'},
    { id: 37, name: 'OREGON', abbreviation: 'OR'},
    { id: 38, name: 'PENNSYLVANIA', abbreviation: 'PA'},
    { id: 39, name: 'RHODE ISLAND', abbreviation: 'RI'},
    { id: 40, name: 'SOUTH CAROLINA', abbreviation: 'SC'},
    { id: 41, name: 'SOUTH DAKOTA', abbreviation: 'SD'},
    { id: 42, name: 'TENNESSEE', abbreviation: 'TN'},
    { id: 43, name: 'TEXAS', abbreviation: 'TX'},
    { id: 44, name: 'UTAH', abbreviation: 'UT'},
    { id: 45, name: 'VERMONT', abbreviation: 'VT'},
    { id: 46, name: 'VIRGINIA', abbreviation: 'VA'},
    { id: 47, name: 'WASHINGTON', abbreviation: 'WA'},
    { id: 48, name: 'WEST VIRGINIA', abbreviation: 'WV'},
    { id: 49, name: 'WISCONSIN', abbreviation: 'WI'},
    { id: 50, name: 'WYOMING', abbreviation: 'WY' }
];


export default US_STATES;

